# Spring Boot configuration
spring:
  # Database
  datasource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://flora.db.elephantsql.com/mhcfhwvl
    username: mhcfhwvl
    password: xt6afeErYd7Wbo7yt4gi61UsJ5fEpHl0
  # JPA properties
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Server configuration
server:
  port: 8080
# Security configuration
security:
  user:
    name: user
password: user
